language: node_js
node_js:
  - '8'
  - '9'
  - '10'
script:
  - ls
  # - yarn lint
  # - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
